apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: my-app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}